apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- falco-driver/modern_ebpf/configmap.yaml
- falco-driver/modern_ebpf/daemonset.yaml
- falco-driver/modern_ebpf/redis.yaml
- falco-driver/modern_ebpf/stress-ng.yaml
- falco-driver/modern_ebpf/falco-event-generator.yaml
- falco-driver/ebpf/configmap.yaml
- falco-driver/ebpf/daemonset.yaml
- falco-driver/ebpf/redis.yaml
- falco-driver/ebpf/stress-ng.yaml
- falco-driver/ebpf/falco-event-generator.yaml
- falco-driver/kmod/configmap.yaml
- falco-driver/kmod/daemonset.yaml
- falco-driver/kmod/redis.yaml
- falco-driver/kmod/stress-ng.yaml
- falco-driver/kmod/falco-event-generator.yaml
- falco-generic/serviceaccount.yaml
- falco-generic/falcoctl-configmap.yaml
