apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-event-generator-driver-modern-ebpf
  namespace: falco
  labels:
    app: falco-event-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falco-event-generator
  template:
    metadata:
      labels:
        app: falco-event-generator
    spec:
      nodeSelector:
        cncf-project-sub: "falco-driver-modern-ebpf"
      containers:
      - name: falco-event-generator
        securityContext:
          {}
        image: "falcosecurity/event-generator:latest"
        imagePullPolicy: IfNotPresent
        command: 
          - /bin/event-generator 
          - run
          - ^syscall
          - --loop
        env:
        - name: FALCO_EVENT_GENERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

