apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-driver-kmod
  namespace: falco
  labels:
    app.kubernetes.io/name: falco-driver-kmod
    app.kubernetes.io/version: "0.37.0"
data:
  logrotate.conf: |-
    /tmp/stats/falco_stats.jsonl {
      rotate 3
      su root adm
      size 30M
    }
    /tmp/falco/events.jsonl {
      rotate 3
      su root adm
      size 30M
    }
  # --- falco.yaml ---
  # The following configs deviate from the default falco.yaml
  # `file_output` is enabled
  # `json_output` is enabled
  # `json_include_output_property` set to false
  # `json_include_tags_property` set to false
  # `metrics` is enabled, interval: 30m w/ file output
  # `priority` set to "info" instead of "debug"
  # `webserver` is disabled
  falco.yaml: |-
    rules_file:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/falco_rules.local.yaml
      - /etc/falco/rules.d
    engine:
      kind: kmod
      kmod:
        buf_size_preset: 4
        drop_failed_exit: false
      ebpf:
        probe: ${HOME}/.falco/falco-bpf.o
        buf_size_preset: 4
        drop_failed_exit: false
      modern_ebpf:
        cpus_for_each_buffer: 2
        buf_size_preset: 4
        drop_failed_exit: false
      replay:
        capture_file: ""
      gvisor:
        config: ""
        root: ""
    watch_config_files: true
    time_format_iso_8601: false
    priority: info
    json_output: true
    json_include_output_property: false
    json_include_tags_property: false
    buffered_outputs: false
    rule_matching: first
    outputs_queue:
      capacity: 0
    stdout_output:
      enabled: true
    syslog_output:
      enabled: true
    file_output:
      enabled: true
      keep_alive: false
      filename: /tmp/falco/events.jsonl
    webserver:
      enabled: false
    log_stderr: true
    log_syslog: true
    log_level: info
    libs_logger:
      enabled: false
      severity: debug
    output_timeout: 2000
    syscall_event_timeouts:
      max_consecutives: 1000
    metrics:
      enabled: true
      interval: 30m
      output_rule: true
      output_file: /tmp/stats/falco_stats.jsonl
      resource_utilization_enabled: true
      state_counters_enabled: true
      kernel_event_counters_enabled: true
      libbpf_stats_enabled: true
      convert_memory_to_mb: true
      include_empty_values: false
    base_syscalls:
      custom_set: []
      repair: false
