apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-driver-bpf
  namespace: falco
  labels:
    app.kubernetes.io/name: falco-driver-bpf
    app.kubernetes.io/version: "0.37.0"
data:
  logrotate.conf: |-
    /tmp/stats/falco_stats.jsonl {
      rotate 3
      su root adm
      size 30M
    }
    /tmp/falco/events.jsonl {
      rotate 3
      su root adm
      size 30M
    }
  # --- falco.yaml ---
  # The following configs deviate from the default falco.yaml
  # `file_output` is enabled
  # `json_output` is enabled
  # `metrics` is enabled, interval: 2m
  # `priority` set to "info" instead of "debug"
  # `webserver` is disabled
  falco.yaml: |-
    base_syscalls:
      custom_set: []
      repair: false
    buffered_outputs: false
    file_output:
      enabled: true
      filename: /tmp/falco/events.jsonl
      keep_alive: false
    grpc:
      bind_address: unix:///run/falco/falco.sock
      enabled: false
      threadiness: 0
    grpc_output:
      enabled: false
    http_output:
      ca_bundle: ""
      ca_cert: ""
      ca_path: /etc/falco/certs/
      client_cert: /etc/falco/certs/client/client.crt
      client_key: /etc/falco/certs/client/client.key
      echo: false
      enabled: false
      insecure: false
      mtls: false
      url: ""
      user_agent: falcosecurity/falco
    json_include_output_property: false
    json_include_tags_property: false
    json_output: true
    libs_logger:
      enabled: false
      severity: debug
    load_plugins: []
    log_level: info
    log_stderr: true
    log_syslog: true
    metrics:
      convert_memory_to_mb: true
      enabled: true
      include_empty_values: false
      interval: 2m
      kernel_event_counters_enabled: true
      libbpf_stats_enabled: true
      output_rule: true
      output_file: /tmp/stats/falco_stats.jsonl
      resource_utilization_enabled: true
    modern_bpf:
      cpus_for_each_syscall_buffer: 2
    output_timeout: 2000
    outputs_queue:
      capacity: 0
    plugins:
    - init_config: null
      library_path: libk8saudit.so
      name: k8saudit
      open_params: http://:9765/k8s-audit
    - library_path: libcloudtrail.so
      name: cloudtrail
    - init_config: ""
      library_path: libjson.so
      name: json
    priority: info
    program_output:
      enabled: false
      keep_alive: false
      program: 'jq ''{text: .output}'' | curl -d @- -X POST https://hooks.slack.com/services/XXX'
    rule_matching: first
    rules_file:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/rules.d
    stdout_output:
      enabled: true
    syscall_buf_size_preset: 4
    syscall_drop_failed_exit: false
    syscall_event_drops:
      actions:
      - log
      - alert
      max_burst: 1
      rate: 0.03333
      simulate_drops: false
      threshold: 0.1
    syscall_event_timeouts:
      max_consecutives: 1000
    syslog_output:
      enabled: true
    time_format_iso_8601: false
    watch_config_files: true
    webserver:
      enabled: false
      k8s_healthz_endpoint: /healthz
      listen_port: 8765
      ssl_certificate: /etc/falco/falco.pem
      ssl_enabled: false
      threadiness: 0
